// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Application.Data.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220204103437_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Application.Data.DataObjects.ApplicantDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AddressCurrent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CityBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INN")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PassportNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SNILS")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Applicant");
                });

            modelBuilder.Entity("Application.Data.DataObjects.ApplicationDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApplicantId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ApplicationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApplicationNum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchBank")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchBankAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditManagerId")
                        .HasColumnType("int");

                    b.Property<int?>("RequestedCreditId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScoringDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("ScoringStatus")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ApplicantId");

                    b.HasIndex("RequestedCreditId");

                    b.ToTable("Application");
                });

            modelBuilder.Entity("Application.Data.DataObjects.RequestedCreditDTO", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("AnnualSalary")
                        .HasColumnType("float");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CreditType")
                        .HasColumnType("int");

                    b.Property<double>("MonthSalary")
                        .HasColumnType("float");

                    b.Property<double>("RequestedAmount")
                        .HasColumnType("float");

                    b.Property<string>("RequestedCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestedCredit");
                });

            modelBuilder.Entity("Application.Data.DataObjects.ApplicationDTO", b =>
                {
                    b.HasOne("Application.Data.DataObjects.ApplicantDTO", "Applicant")
                        .WithMany()
                        .HasForeignKey("ApplicantId");

                    b.HasOne("Application.Data.DataObjects.RequestedCreditDTO", "RequestedCredit")
                        .WithMany()
                        .HasForeignKey("RequestedCreditId");

                    b.Navigation("Applicant");

                    b.Navigation("RequestedCredit");
                });
#pragma warning restore 612, 618
        }
    }
}
